### PR TITLE
Update Gravitee project dependencies

### PR DESCRIPTION
**Pull request by larsnaesbye**
Updates a bunch of the common Gravitee dependecies to newer available versions.

### CODE REVIEW

**Comment by brasseld** [comment]
Hi @larsnaesbye 

Thanks for doing this update stuff.

FYI, we are looking to release a new version of file-reporter to support json output, csv output and msgpack output very soon. This will also output the different metrics of the platform, not only request metrics.

As a side note, there will be no more access-log output from this reporter.

**Comment by larsnaesbye** [comment]
Hi @brasseld 

That sounds amazing. Since I have a task adjusting file-reporter to [my agency's](https://eng.sdfe.dk/datadistribution/the-danish-map-supply/) needs, I will probably make some more pull requests to this reporter :-)

**Comment by brasseld** [comment]
The goal of that new version is to reduce memory pressure (up to 4-500%) and avoid to oush to elasticsearch directly. So that would be a great improvement for most of the users!
Will keep in touch with that.
Also, feel free if tou want to have an open discussion about all those stuff.

**Comment by larsnaesbye** [comment]
This sounds like a real good idea to do. Is it something you're planning for 3.2 or 3.3?

**Comment by larsnaesbye** [comment]
If you're doing CSV, please let the separator be configurable. When logging user-agent there is often both comma and semi-colon in the string, so it's useful to be able to define a character that is not one of those two :-)

**Comment by larsnaesbye** [comment]
I presume this is the one: https://github.com/gravitee-io/issues/issues/4236

**Comment by larsnaesbye** [comment]
@brasseld I see that your work with 2.0 is beginning in the  branch `#4236-file-reporter-2x` so I think I'll close this PR and see if I can help there instead :-)

**Pull request closed without merging**
